package com.ygy.mapper;

import com.ygy.model.Sysrole;
import com.ygy.model.SysroleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysroleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int countByExample(SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int deleteByExample(SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int insert(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int insertSelective(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    List<Sysrole> selectByExample(SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    Sysrole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int updateByExampleSelective(@Param("record") Sysrole record, @Param("example") SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int updateByExample(@Param("record") Sysrole record, @Param("example") SysroleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int updateByPrimaryKeySelective(Sysrole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysRole
     *
     * @mbggenerated Tue Dec 05 19:31:30 CST 2017
     */
    int updateByPrimaryKey(Sysrole record);
    Sysrole selectById1(Long id);
}